subjects = {
    'HU111': {'name': 'English in specialty', 'credits': 2, 'program': 'General Education', 'pre_req': None},
    'HU113': {'name': 'Human rights and the fight against corruption', 'credits': 2, 'program': 'General Education', 'pre_req': None},
    'HU121': {'name': 'Fundamentals of management', 'credits': 3, 'program': 'General Education', 'pre_req': None},
    'MA111': {'name': 'Calculus', 'credits': 3, 'program': 'Engineering', 'pre_req': None},
    'IT111': {'name': 'Electronics', 'credits': 3, 'program': 'Information Technology', 'pre_req': None},
    'CS141': {'name': 'Fundamentals of computer science', 'credits': 2, 'program': 'Computer Science', 'pre_req': None},
    'PH111': {'name': 'Optical physics', 'credits': 3, 'program': 'Physics', 'pre_req': None},

    'HU112': {'name': 'Scientific and technical report writing', 'credits': 2, 'program': 'General Education', 'pre_req': None},
    'CS111': {'name': 'Discrete structures', 'credits': 3, 'program': 'Computer Science', 'pre_req': 'MA111'},
    'MA113': {'name': 'Linear algebra', 'credits': 3, 'program': 'Engineering', 'pre_req': 'MA111'},
    'ST121': {'name': 'Probability and statistics', 'credits': 3, 'program': 'General Education', 'pre_req': 'MA111'},
    'CS142': {'name': 'Programming', 'credits': 3, 'program': 'Computer Science', 'pre_req': 'CS141'},
    'CS181': {'name': 'E-learning', 'credits': 2, 'program': 'Computer Science', 'pre_req': None},
    'CS171': {'name': 'Mutimedia', 'credits': 2, 'program': 'Computer Science', 'pre_req': None},

    'CS241': {'name': 'Advanced programming', 'credits': 3, 'program': 'Computer Science', 'pre_req': 'CS142'},
    'CS211': {'name': 'Data structures', 'credits': 3, 'program': 'Computer Science', 'pre_req': 'CS142'},
    'CS222': {'name': 'Logic design', 'credits': 3, 'program': 'Computer Science', 'pre_req': 'IT111'},
    'IT211': {'name': 'Data communication', 'credits': 3, 'program': 'Information Technology', 'pre_req': 'MA113'},
    'IS241': {'name': 'System analysis and design', 'credits': 3, 'program': 'Information Systems', 'pre_req': None},
    'IT112': {'name': 'Signals and systems', 'credits': 3, 'program': 'Information Technology', 'pre_req': 'MA113'},

    'CS223': {'name': 'Operating systems', 'credits': 3, 'program': 'Computer Science', 'pre_req': 'CS142'},
    'CS251': {'name': 'Software engineering', 'credits': 2, 'program': 'Computer Science', 'pre_req': 'CS241'},
    'IT241': {'name': 'Computer network', 'credits': 3, 'program': 'Information Technology', 'pre_req': 'IT211'},
    'IS221': {'name': 'Database system', 'credits': 3, 'program': 'Information Systems', 'pre_req': 'CS241'},
    'IS242': {'name': 'Modeling and simulation', 'credits': 3, 'program': 'Information Systems', 'pre_req': 'IS241'},
    'CS221': {'name': 'File organization and processing', 'credits': 2, 'program': 'Computer Science', 'pre_req': 'CS142'},
    'HU332': {'name': 'Creative thinking', 'credits': 3, 'program': 'General Education', 'pre_req': None},

    'CS351': {'name': 'Computer graphics', 'credits': 3, 'program': 'Computer Science', 'pre_req': 'CS142'},
    'CS381': {'name': 'Artificial intelligence', 'credits': 3, 'program': 'Computer Science', 'pre_req': 'CS241'},
    'IT441': {'name': 'Information and computer networks security', 'credits': 3, 'program': 'Information Technology', 'pre_req': 'IT241'},
    'CS321': {'name': 'Computer architecture and organization', 'credits': 3, 'program': 'Computer Science', 'pre_req': 'CS222'},
    'IT281': {'name': 'Internet technology', 'credits': 3, 'program': 'Information Technology', 'pre_req': 'IT241'},
    'CS311': {'name': 'Algorithms', 'credits': 3, 'program': 'Computer Science', 'pre_req': 'CS142'},
    'IT371': {'name': 'Computer architecture', 'credits': 3, 'program': 'Information Technology', 'pre_req': 'CS222'},
    'IS321': {'name': 'Advanced database systems', 'credits': 3, 'program': 'Information Systems', 'pre_req': 'IS221'},
    'IS341': {'name': 'Advanced analysis and design of information systems', 'credits': 3, 'program': 'Information Systems', 'pre_req': 'CS251'},

    'CS331': {'name': 'Concepts of porgramming languages', 'credits': 3, 'program': 'Computer Science', 'pre_req': 'CS221'},
    'CS482': {'name': 'Genetic algorithms', 'credits': 3, 'program': 'Computer Science', 'pre_req': 'MA113'},
    'CS382': {'name': 'Pattern recognition', 'credits': 3, 'program': 'Computer Science', 'pre_req': 'IT112'},
    'IT311': {'name': 'Digital signals processing', 'credits': 3, 'program': 'Information Technology', 'pre_req': 'IT112'},
    'MA315': {'name': 'Numerical methods', 'credits': 3, 'program': 'Engineering', 'pre_req': 'MA113'},
    'CS391': {'name': 'Advanced software engineering', 'credits': 3, 'program': 'Computer Science', 'pre_req': 'CS251'},
    'IT342': {'name': 'Communication technology', 'credits': 3, 'program': 'Information Technology', 'pre_req': 'IT211'},
    'IT422': {'name': 'Wireless and mobile networks', 'credits': 3, 'program': 'Information Technology', 'pre_req': 'IS341'},
    'IS322': {'name': 'Data storage and retrieval', 'credits': 3, 'program': 'Information Systems', 'pre_req': 'IS321'},
    'IS342': {'name': 'Advanced analysis and design of information systems', 'credits': 3, 'program': 'Information Systems', 'pre_req': 'IS341'},
    'IS424': {'name': 'Data warehousing', 'credits': 3, 'program': 'Information Systems', 'pre_req': 'IS321'},
    'IS451': {'name': 'Geographic information systems', 'credits': 3, 'program': 'Information Systems', 'pre_req': 'IS321'},
    'IT381': {'name': 'Internet applications', 'credits': 3, 'program': 'Information Technology', 'pre_req': 'IT281'},

    'CS451': {'name': 'mage processing', 'credits': 3, 'program': 'Computer Science', 'pre_req': 'IT311'},
    'CS471': {'name': 'Advanced multimedia', 'credits': 3, 'program': 'Computer Science', 'pre_req': 'CS171'},
    'CS421': {'name': 'Parallel processing', 'credits': 3, 'program': 'Computer Science', 'pre_req': 'CS321'},
    'CS463': {'name': 'Project-1', 'credits': 3, 'program': 'Computer Science', 'pre_req': 'Pass 3 levels'},
    'CS452': {'name': 'Computer vision', 'credits': 3, 'program': 'Computer Science', 'pre_req': 'CS351'},
    'CS484': {'name': 'Machine learning', 'credits': 3, 'program': 'Computer Science', 'pre_req': 'CS381'},
    'IT341': {'name': 'Advanced computers networks', 'credits': 3, 'program': 'Information Technology', 'pre_req': 'IT241'},
    'IT463': {'name': 'Selected Topics in information technology', 'credits': 3, 'program': 'Information Technology', 'pre_req': None},
    'IS422': {'name': 'Database design', 'credits': 3, 'program': 'Information Systems', 'pre_req': 'IS321'},
    'IS331': {'name': 'Management information systems', 'credits': 3, 'program': 'Information Systems', 'pre_req': 'IS321'},
    'IS441': {'name': 'Data mining', 'credits': 3, 'program': 'Information Systems', 'pre_req': 'IS321'},
    'IS463': {'name': 'Selected topics in information systems', 'credits': 3, 'program': 'Information Systems', 'pre_req': None},

    'CS481': {'name': 'Neural networks', 'credits': 3, 'program': 'Computer Science', 'pre_req': 'MA113'},
    'CS483': {'name': 'Knowledge based systems', 'credits': 3, 'program': 'Computer Science', 'pre_req': 'CS381'},
    'CS464': {'name': 'Project-2', 'credits': 3, 'program': 'Computer Science', 'pre_req': 'CS463'},
    'CS441': {'name': 'Compilers', 'credits': 3, 'program': 'Computer Science', 'pre_req': 'CS331'},
    'CS442': {'name': 'Natural language processing', 'credits': 3, 'program': 'Computer Science', 'pre_req': 'CS381'},
    'IT452': {'name': 'Embedded systems', 'credits': 3, 'program': 'Information Technology', 'pre_req': 'IT372'},
    'IT451': {'name': 'Virtual reality', 'credits': 3, 'program': 'Information Technology', 'pre_req': 'CS351'},
    'IS421': {'name': 'Distributed database', 'credits': 3, 'program': 'Information Systems', 'pre_req': 'IS321'},
    'IS432': {'name': 'Quality assurance of information systems and programming', 'credits': 3, 'program': 'Information Systems', 'pre_req': 'IS342'}
}


Data = [4, 1, 2.95, 0,
        59, 60, 70, 76, 74, 81, 73,
        'pc', 'pc', 'pc', 'pc', 'pc', 'pc', 'pc',
        63, 66, 65, 78, 74, 86,
        80, 93, 82, 80, 92, 83, 85,
        90, 91, 83, 82, 77, 81, None, None, None, 69, 74, 80, 87, 77, 89, None,
        None, None, None, None, None, None, 70, 90, 88, 87, 84, None, None,
        None, None, None, None, None, None, None, None, None, None, None,
        None, None, None]

Data_1 = [1, 2, 2.95, 1,
          60, 60, 70, 70, 66, 61, 60,
          'pc', 'pc', 'pc', 'pc', 'pc', 'pc', 'pc',
          None, None, None, None, None, None,
          None, None, None, None, None, None, None,
          None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None,
          None, None, None, None, None, None, None, None, None, None, None, None, None,
          None, None, None, None, None, None, None, None, None, None, None,
          None, None, None]


Data_2 = [3, 1, 2.8, 3,
          87, 72, 70, 80, 66, 61, 73,
          'pc', 'pc', 'pc', 'pc', 'pc', 'pc', 'pc',
          70, 60, 75, 82, 83, 79,
          70, 60, 75, 82, 83, 79, 66,
          None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None,
          None, None, None, None, None, None, None, None, None, None, None, None, None,
          None, None, None, None, None, None, None, None, None, None, None,
          None, None, None]
# 2	2	3.18	it	85	79	70	92	72	90	67	pc	pc	pc	pc	pc	pc	pc	73	81	87	96	79	95	83	99	94	96	85	86	87

# firest level firset semeseter
Data_3 = [0, 0, 0, 1,
          None, None, None, None, None, None, None,
          None, None, None, None, None, None, None,
          None, None, None, None, None, None,
          None, None, None, None, None, None, None,
          None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None,
          None, None, None, None, None, None, None, None, None, None, None, None, None,
          None, None, None, None, None, None, None, None, None, None, None,
          None, None, None]
Data_4 = [1, 1, 2.6, 1,
          87, 72, 70, 60, 66, 61, 73,
          None, None, None, None, None, None, None,
          None, None, None, None, None, None,
          None, None, None, None, None, None, None,
          None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None,
          None, None, None, None, None, None, None, None, None, None, None, None, None,
          None, None, None, None, None, None, None, None, None, None, None,
          None, None, None]

Data_5 = [1, 2, 2.6, 1,
          87, 72, 70, 90, 70, 61, 73,
          'pc', 'pc', 'pc', 'pc', 'pc', 'pc', 'pc',
          None, None, None, None, None, None,
          None, None, None, None, None, None, None,
          None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None,
          None, None, None, None, None, None, None, None, None, None, None, None, None,
          None, None, None, None, None, None, None, None, None, None, None,
          None, None, None]
Data_6 = [2, 1, 2.5, 1,
          87, 72, 70, 44, 65, 61, 73,
          'pc', 'pc', 'pc', 'pc', 'pc', 'pc', 'pc',
          70, 60, 80, 82, 80, 80,
          None, None, None, None, None, None, None,
          None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None,
          None, None, None, None, None, None, None, None, None, None, None, None, None,
          None, None, None, None, None, None, None, None, None, None, None,
          None, None, None]
Data_7 = [2, 2, 2.5, 3,
          87, 72, 70, 70, 70, 61, 73,
          'pc', 'pc', 'pc', 'pc', 'pc', 'pc', 'pc',
          70, 60, 75, 82, 83, 79,
          70, 60, 75, 82, 83, 79, 66,
          None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None,
          None, None, None, None, None, None, None, None, None, None, None, None, None,
          None, None, None, None, None, None, None, None, None, None, None,
          None, None, None]
Data_8 = [3.0, 1.0, 3.64, 2,
          88.0, 79.0, 69.0, 94.0, 91.0, 92.0, 79.0,
          'pc', 'pc', 'pc', 'pc', 'pc', 'pc', 'pc',
          68.0, 89.0, 89.0, 99.0, 82.0, 95.0,
          97.0, 97.0, 96.0, 97.0, 95.0, 93.0, 91.0,
          None, 99.0, 86.0, None, 94.0, 86.0, None, 55.0, 83.0, None, None, None, None,
          None, None, None, None, None, None, None, None, None, None, None, None, None, None, None,
          None, None, None, None, None, None, None, None, None, None, None, None, None, None, None]
